# Generated by Django 6.1 on 2026-08-10 13:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mobile_money_number', models.CharField(max_length=32)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'Halopesa')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(help_text='Stable code shared with the ledger rows for this payout.', max_length=40, unique=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal request',
                'verbose_name_plural': 'Withdrawal requests',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='wd_user_status_idx'), models.Index(fields=['status', 'created_at'], name='wd_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('5000.00'))), name='wd_amount_minimum')],
            },
        ),
    ]
