# Generated by Django 6.1 on 2026-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_message',
            field=models.TextField(blank=True, default='', help_text='Human-readable message/notes returned by the payout call.'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_reference',
            field=models.CharField(blank=True, default='', help_text='ClickPesa payout id returned by the gateway.', max_length=64),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_status',
            field=models.CharField(blank=True, default='', help_text='ClickPesa payout status: SUCCESS, AUTHORIZED, FAILED, PENDING or UNAVAILABLE when the gateway could not be used.', max_length=32),
        ),
    ]
