# Generated by Django 6.1 on 2026-08-28 13:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawalrequest_payout_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawalrequest',
            name='wd_amount_minimum',
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('500.00'))), name='wd_amount_minimum'),
        ),
    ]
