# Generated by Django 6.1 on 2026-08-09 11:48

import catalog.models
import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=catalog.models.product_image_upload_to, validators=[catalog.validators.validate_image_extension, catalog.validators.validate_image_mime, catalog.validators.validate_image_size, catalog.validators.validate_image_content]),
        ),
    ]
