"""
Django settings for the ReuseHub backend.

Generated by 'django-admin startproject' using Django 6.1.

All secrets and environment-specific values come from environment variables
(via django-environ). See backend/.env.example for the full list of variables.
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Environment ----------------------------------------------------------
# Read .env (never committed). Values are overridden by real environment
# variables when both exist.
env = environ.Env(
    DEBUG=(bool, False),
)

environ.Env.read_env(BASE_DIR / ".env")

# --- Django core ----------------------------------------------------------

# Allow all hosts (development/demo). Not read from .env so it never depends
# on deployment-specific configuration; on Render the load balancer hostname is
# covered too. Narrow this down (e.g. to your domain) for a hard production.
ALLOWED_HOSTS = ["*"]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "generate_secret_key_and_change_me_if_you_dont_love_sultan"


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG defaults to False and is only True when explicitly set in .env / env.
DEBUG = True

# Fail-fast guard: refuse to run with debug on unless the environment
# explicitly allows it. This stops a stray DEBUG=True in a live deployment.

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "whitenoise.runserver_nostatic",
    # Local apps
    "core",
    "accounts",
    "catalog",
    "cart",
    "orders",
    "payments",
    "wallet",
    "withdrawals",
    "chat",
    "notifications",
    "reviews",
    "adminpanel",
    "auditlog",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# --- Database ---------------------------------------------------------------
# SQLite is the default so the project runs anywhere with zero external
# services (including a free Render deploy). PostgreSQL can still be used by
# setting USE_SQLITE=False and providing the POSTGRES_* variables.
if env.bool("USE_SQLITE", default=True):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            # Optional env override lets a managed host (e.g. Render) place the
            # DB on a persistent disk; defaults to ./backend/db.sqlite3.
            "NAME": env("SQLITE_DB_PATH", default=str(BASE_DIR / "db.sqlite3")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("POSTGRES_DB", default="reusehub"),
            "USER": env("POSTGRES_USER", default="reusehub"),
            "PASSWORD": env("POSTGRES_PASSWORD", default="1234"),
            "HOST": env("POSTGRES_HOST", default="localhost"),
            "PORT": env("POSTGRES_PORT", default="5432"),
        }
    }

# --- Authentication / JWT ----------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": env("THROTTLE_ANON_RATE", default="30/min"),
        "user": env("THROTTLE_USER_RATE", default="120/min"),
        # Tighter, per-endpoint scopes set on sensitive views.
        "auth_login": env("THROTTLE_AUTH_LOGIN_RATE", default="10/min"),
        "auth_password_reset": "5/min",
        "payment_initiate": env("THROTTLE_PAYMENT_INITIATE_RATE", default="60/min"),
    },
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    # PageNumberPagination (documented choice) — see catalog/pagination.py.
    "DEFAULT_PAGINATION_CLASS": "catalog.pagination.CatalogPagination",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=env("JWT_ACCESS_TOKEN_LIFETIME_DAYS", default=1)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=7)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# --- CORS ---------------------------------------------------------------------
# Comma-separated list in env; defaults to the Expo dev servers.
CORS_ALLOWED_ORIGINS = []
CORS_ALLOW_ALL_ORIGINS = True

# --- Password validation -------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# --- Internationalization ------------------------------------------------------
LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True

# --- Static files / media -------------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "media/"
# MEDIA_ROOT can be overridden via env so a managed host (e.g. Render) can
# point it at a persistent disk. Defaults to ./backend/media for local dev.
MEDIA_ROOT = Path(env("MEDIA_ROOT", default=str(BASE_DIR / "media")))

# Uploaded product images go to local disk (MEDIA_ROOT) — the simplest realistic
# option for a final-year deployment. In production, serve MEDIA_ROOT from the
# same host (Nginx/gunicorn) or move to object storage when outgrowing the box.
# See docs/DEPLOYMENT.md.

# --- Security hardening --------------------------------------------------------
# Secure headers / redirects are gated behind SECURE_HTTP=True so local dev
# (http://localhost) keeps working. Enable for any TLS-terminated deployment.



# --- Payments / ClickPesa ----------------------------------------------------
# Credentials are read from the environment only and are never sent to clients.
# Flow and payloads documented in docs/CLICKPESA_INTEGRATION.md.
CLICKPESA_BASE_URL = env("CLICKPESA_BASE_URL", default="https://api.clickpesa.com/third-parties")
# HTTP timeout (seconds) for outbound ClickPesa calls (USSD-push initiation,
# status queries). Raised from the default to tolerate slow mobile-money
# gateway responses. Set via CLICKPESA_TIMEOUT in .env when needed.
CLICKPESA_TIMEOUT = env.int("CLICKPESA_TIMEOUT", default=45)
CLICKPESA_CLIENT_ID = env("CLICKPESA_CLIENT_ID", default="")
CLICKPESA_API_KEY = env("CLICKPESA_API_KEY", default="")
CLICKPESA_CHECKSUM_SECRET = env(
    "CLICKPESA_CHECKSUM_SECRET", default=env("CLICKPESA_WEBHOOK_SECRET", default="")
)
CLICKPESA_WEBHOOK_SECRET = CLICKPESA_CHECKSUM_SECRET
CLICKPESA_CURRENCY = env("CLICKPESA_CURRENCY", default="TZS")

# When False (default), withdrawal completions record payouts as UNAVAILABLE
# instead of calling ClickPesa. Enable only when the merchant has PAYOUT API
# access and real balance — see docs/CLICKPESA_INTEGRATION.md.
CLICKPESA_PAYOUTS_ENABLED = env.bool("CLICKPESA_PAYOUTS_ENABLED", default=False)

NGROK_PUBLIC_URL = env(
    "NGROK_PUBLIC_URL", default=env("CLICKPESA_WEBHOOK_BASE_URL", default="")
).rstrip("/")
CLICKPESA_WEBHOOK_BASE_URL = NGROK_PUBLIC_URL

# --- Defaults ---------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
