# Generated by Django 6.1 on 2026-08-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
    ]
