# Generated by Django 6.1 on 2026-08-09 14:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_orderitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('platform_fee', 'Platform fee'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('reference', models.CharField(blank=True, help_text="Free-text reference, e.g. 'order-item:42' or a provider reference.", max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger transaction',
                'verbose_name_plural': 'Ledger transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ledger_user_created_idx'), models.Index(fields=['reference'], name='ledger_reference_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_item', 'type'), name='ledger_unique_order_item_type')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0.00'))), name='wallet_balance_non_negative')],
            },
        ),
    ]
