# Generated by Django 6.1 on 2026-08-09 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, help_text='Identifier for anonymously-created carts.', max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('session_key__isnull', True)), models.Q(('owner__isnull', True), ('session_key__isnull', False)), _connector='OR'), name='cart_owner_or_session_key'),
        ),
    ]
