# Generated by Django 6.1 on 2026-09-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredMedia',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stored media',
                'verbose_name_plural': 'stored media',
            },
        ),
    ]
