# Generated by Django 6.1 on 2026-08-15 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auth.login', 'Login'), ('auth.login_failed', 'Login failed'), ('auth.logout', 'Logout'), ('auth.register', 'Registration'), ('auth.profile_update', 'Profile update'), ('product.create', 'Product created'), ('product.update', 'Product updated'), ('product.delete', 'Product deleted'), ('order.create', 'Order created'), ('order.transition', 'Order status changed'), ('payment.initiate', 'Payment initiated'), ('payment.success', 'Payment succeeded'), ('payment.failure', 'Payment failed'), ('withdrawal.request', 'Withdrawal requested'), ('withdrawal.transition', 'Withdrawal status changed'), ('admin.user_suspend', 'User suspended'), ('admin.user_activate', 'User activated'), ('admin.product_remove', 'Product removed'), ('admin.category_create', 'Category created'), ('admin.category_update', 'Category updated')], max_length=64)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='auditlog_au_actor_i_e7d961_idx'), models.Index(fields=['action', 'created_at'], name='auditlog_au_action_403129_idx'), models.Index(fields=['target_model', 'target_id'], name='auditlog_au_target__13695c_idx')],
            },
        ),
    ]
