# Generated by Django 6.1 on 2026-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('auth.login', 'Login'), ('auth.login_failed', 'Login failed'), ('auth.logout', 'Logout'), ('auth.register', 'Registration'), ('auth.profile_update', 'Profile update'), ('auth.password_reset_requested', 'Password reset requested'), ('auth.password_reset_completed', 'Password reset completed'), ('product.create', 'Product created'), ('product.update', 'Product updated'), ('product.delete', 'Product deleted'), ('order.create', 'Order created'), ('order.transition', 'Order status changed'), ('payment.initiate', 'Payment initiated'), ('payment.success', 'Payment succeeded'), ('payment.failure', 'Payment failed'), ('withdrawal.request', 'Withdrawal requested'), ('withdrawal.transition', 'Withdrawal status changed'), ('admin.user_suspend', 'User suspended'), ('admin.user_activate', 'User activated'), ('admin.user_update', 'User updated'), ('admin.user_delete', 'User deleted'), ('admin.product_remove', 'Product removed'), ('admin.category_create', 'Category created'), ('admin.category_update', 'Category updated')], max_length=64),
        ),
    ]
