# Generated by Django 6.1 on 2026-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_clickpesa_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='network_channel',
            field=models.CharField(blank=True, default='', help_text='Mobile money channel detected by ClickPesa (e.g. M-PESA, TIGO-PESA, AIRTEL-MONEY, HALOPESA).', max_length=30),
        ),
    ]
