# Generated by Django 6.1 on 2026-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_network_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='network_channel',
            field=models.CharField(blank=True, default='', help_text='Mobile money channel detected by ClickPesa (e.g. M-PESA, TIGO-PESA).', max_length=30),
        ),
    ]
